# Generated by Django 4.2.3 on 2023-12-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPersonalInfo',
            fields=[
                ('studentId', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=5)),
                ('bloodGroup', models.CharField(max_length=5)),
                ('fatherName', models.CharField(max_length=100)),
                ('motherName', models.CharField(max_length=100)),
                ('emailCollege', models.EmailField(max_length=254)),
                ('emailPersonal', models.EmailField(max_length=254)),
                ('DOB', models.DateField()),
                ('registerDate', models.DateField()),
                ('mobileNo', models.BigIntegerField()),
            ],
        ),
    ]
