# Generated by Django 4.2.3 on 2023-12-16 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_studentinfo_registerdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='registerDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
