# Generated by Django 4.2.3 on 2023-12-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_studentinfo_course_studentinfo_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPersonalInfo',
            fields=[
                ('studentId', models.IntegerField(primary_key=True, serialize=False)),
                ('fatherName', models.CharField(max_length=100)),
                ('motherName', models.CharField(max_length=100)),
                ('bloodGroup', models.CharField(default='N/A', max_length=5)),
                ('category', models.CharField(default='N/A', max_length=10)),
                ('profileImg', models.ImageField(default='', upload_to='profileImages/')),
                ('dob', models.DateField(default='')),
            ],
        ),
    ]
