# Generated by Django 4.2.3 on 2023-12-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_studentpersonalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEducationInfo',
            fields=[
                ('studentId', models.IntegerField(primary_key=True, serialize=False)),
                ('instituteName_10', models.CharField(max_length=100)),
                ('board_10', models.CharField(max_length=50)),
                ('markSheet_10', models.ImageField(upload_to='markSheet10/')),
                ('percent_10', models.DecimalField(decimal_places=2, max_digits=4)),
                ('passOutYear_10', models.CharField(max_length=4)),
                ('instituteName_12', models.CharField(max_length=100)),
                ('board_12', models.CharField(max_length=50)),
                ('markSheet_12', models.ImageField(upload_to='markSheet12/')),
                ('percent_12', models.DecimalField(decimal_places=2, max_digits=4)),
                ('passOutYear_12', models.DateField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='college_campus',
            field=models.CharField(default='GEHU-HLD', max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='course_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='studentType',
            field=models.CharField(default='Regular', max_length=50),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='university',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentpersonalinfo',
            name='current_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentpersonalinfo',
            name='permanent_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
