# Generated by Django 4.2.3 on 2023-12-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_studenteducationinfo_studentinfo_college_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenteducationinfo',
            name='tc_migration',
            field=models.ImageField(default='', upload_to='tcMigrations/'),
        ),
    ]
