# Generated by Django 3.1.1 on 2023-12-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_studenteducationinfo_tc_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='specialization',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
