# Generated by Django 3.1.1 on 2023-12-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20231220_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenteducationinfo',
            name='passOutYear_12',
            field=models.CharField(max_length=4),
        ),
    ]
