# Generated by Django 3.1.1 on 2023-12-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20231221_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='university',
            field=models.CharField(default='Graphic Era Hill University', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentpersonalinfo',
            name='profileImg',
            field=models.ImageField(default='profileImages/profile.png', upload_to='profileImages/'),
        ),
    ]
