# Generated by Django 3.1.1 on 2023-12-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20231221_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(default='', max_length=10)),
                ('courseName', models.CharField(default='', max_length=10)),
                ('specialization', models.CharField(default='N/A', max_length=50)),
                ('sem', models.IntegerField()),
                ('timetable', models.FileField(default='', upload_to='timetable/')),
                ('courseType', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='courseType',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='specialization',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='courseId',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
