# Generated by Django 3.1.1 on 2023-12-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20231221_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courseName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='courseType',
            field=models.CharField(default='UG', max_length=50),
        ),
    ]
