# Generated by Django 3.1.1 on 2023-12-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_bca5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bca5',
            name='teacherImg',
            field=models.ImageField(default='profileImages/profile.png', upload_to='teacherProfileImg/'),
        ),
    ]
