# Generated by Django 3.1.1 on 2023-12-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20231221_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenteducationinfo',
            name='studentId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentpersonalinfo',
            name='studentId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
