# Generated by Django 3.1.1 on 2023-12-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20231221_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenteducationinfo',
            name='id',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpersonalinfo',
            name='id',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
    ]
