# Generated by Django 3.1.1 on 2023-12-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20231221_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenteducationinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentpersonalinfo',
            name='id',
        ),
    ]
