# Generated by Django 3.1.1 on 2023-12-21 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20231221_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectsInfo',
            fields=[
                ('subjectId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=100)),
                ('syllabus', models.FileField(default='', upload_to='syllabus/')),
                ('teacherName', models.CharField(max_length=100)),
                ('teacherImg', models.ImageField(default='profileImages/profile.png', upload_to='teacherProfileImg/')),
            ],
        ),
        migrations.DeleteModel(
            name='BCA5',
        ),
        migrations.AddField(
            model_name='studenteducationinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpersonalinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='courseId',
            field=models.CharField(max_length=10, primary_key=True),
        ),
        migrations.AlterField(
            model_name='studenteducationinfo',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentinfo'),
        ),
        migrations.AlterField(
            model_name='studentpersonalinfo',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentinfo'),
        ),
        migrations.AddField(
            model_name='subjectsinfo',
            name='courseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.courses'),
        ),
    ]
