# Generated by Django 3.1.1 on 2023-12-21 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20231221_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feeName', models.CharField(max_length=50)),
                ('dues', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scholarship', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feeFrequency', models.CharField(max_length=30)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentinfo')),
            ],
        ),
    ]
