# Generated by Django 3.1.1 on 2023-12-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_feedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedetails',
            name='feeFrequency',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='feeFrequency',
            field=models.CharField(default='Half-Yearly', max_length=30),
        ),
        migrations.AlterField(
            model_name='feedetails',
            name='sem',
            field=models.IntegerField(),
        ),
    ]
