# Generated by Django 3.1.1 on 2023-12-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_feereceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='feereceipt',
            name='feeDescription',
            field=models.CharField(default='semester fees', max_length=200),
            preserve_default=False,
        ),
    ]
