# Generated by Django 3.1.1 on 2023-12-21 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_feereceipt_feedescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='feereceipt',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
