# Generated by Django 3.1.1 on 2023-12-21 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_feereceipt_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='circular/')),
                ('issuedBy', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=500)),
                ('dateTo', models.DateField(default=django.utils.timezone.now)),
                ('dateFrom', models.DateField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='notification/')),
                ('link', models.CharField(max_length=1000)),
                ('issuedBy', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='notification/')),
                ('issuedBy', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
