# Generated by Django 3.1.1 on 2023-12-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='resultMid',
        ),
        migrations.AddField(
            model_name='result',
            name='type',
            field=models.CharField(default='mid', max_length=5),
            preserve_default=False,
        ),
    ]
