# Generated by Django 3.1.1 on 2023-12-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20231221_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitcard',
            name='back_file',
            field=models.FileField(default='None', upload_to='resultEnd/'),
        ),
        migrations.AlterField(
            model_name='admitcard',
            name='normal_file',
            field=models.FileField(default='None', upload_to='resultEnd/'),
        ),
        migrations.AlterField(
            model_name='result',
            name='file',
            field=models.FileField(default='None', upload_to='resultEnd/'),
        ),
    ]
