# Generated by Django 3.1.1 on 2023-12-22 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20231222_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitcard',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentinfo'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('status', models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present'), ('No Class', 'No Class')], default='No Class', max_length=10)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentinfo')),
            ],
        ),
    ]
