# Generated by Django 3.1.1 on 2023-12-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20231222_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
    ]
